<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{{ $title ?? 'Keuangan' }}</title><link rel="stylesheet" href="https://cdn-uicons.flaticon.com/2.6.0/uicons-regular-rounded/css/uicons-regular-rounded.css"><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,400,0,0">@if(file_exists(public_path('build/manifest.json'))) @vite(['resources/css/app.css','resources/js/app.js']) @endif<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script></head><body>
@auth
<header class="topbar"><a class="brand" href="{{ route('dashboard') }}"><span class="brand-mark">↗</span><span>Keuangan<span class="brand-dot">.</span></span></a><nav><a href="{{ route('dashboard') }}" class="{{ request()->routeIs('dashboard')?'active':'' }}">Ringkasan</a><a href="{{ route('categories') }}" class="{{ request()->routeIs('categories')?'active':'' }}">Kategori</a><a href="{{ route('members') }}" class="{{ request()->routeIs('members')?'active':'' }}">Anggota</a><a href="{{ route('telegram') }}" class="{{ request()->routeIs('telegram')?'active':'' }}">Telegram</a><a href="{{ route('settings') }}" class="{{ request()->routeIs('settings')?'active':'' }}">Pengaturan</a><a href="{{ route('profile') }}" class="{{ request()->routeIs('profile')?'active':'' }}">Profil</a><form method="post" action="{{ route('logout') }}">@csrf<button class="nav-logout">Keluar</button></form></nav><div class="user-chip"><span>{{ strtoupper(substr(auth()->user()->username,0,1)) }}</span>{{ auth()->user()->username }}</div></header>
<nav class="bottom-nav" aria-label="Navigasi utama mobile"><a href="{{ route('dashboard') }}" class="{{ request()->routeIs('dashboard')?'active':'' }}"><i class="fi fi-rr-home" aria-hidden="true"></i><small>Beranda</small></a><a href="{{ route('categories') }}" class="{{ request()->routeIs('categories')?'active':'' }}"><i class="fi fi-rr-apps" aria-hidden="true"></i><small>Kategori</small></a><a href="{{ route('dashboard',['open'=>'transaction']) }}" class="add-transaction" aria-label="Tambah transaksi"><i class="fi fi-rr-plus" aria-hidden="true"></i><small>Tambah</small></a><a href="{{ route('profile') }}" class="{{ request()->routeIs('profile')?'active':'' }}"><i class="fi fi-rr-user" aria-hidden="true"></i><small>Profil</small></a><form method="post" action="{{ route('logout') }}">@csrf<button><i class="fi fi-rr-sign-out-alt" aria-hidden="true"></i><small>Keluar</small></button></form></nav>
@endauth
<main class="page">{{ $slot ?? '' }} @yield('content')</main>
<script>
const closeModal = (dialog) => { if (!dialog || !dialog.open || dialog.classList.contains('closing')) return; dialog.classList.add('closing'); setTimeout(() => { dialog.classList.remove('closing'); dialog.close(); }, 180); };
document.querySelectorAll('[data-modal]').forEach(button => button.addEventListener('click', () => document.getElementById(button.dataset.modal)?.showModal()));
document.querySelectorAll('.add-transaction').forEach(button => button.addEventListener('click', event => { const modal = document.getElementById('transactionModal'); if (modal) { event.preventDefault(); modal.showModal(); } }));
if (new URLSearchParams(window.location.search).get('open') === 'transaction') document.getElementById('transactionModal')?.showModal();
document.querySelectorAll('[data-detail]').forEach(item => item.addEventListener('click', event => { if (event.target.closest('form,button,a')) return; const modal = document.getElementById('transactionDetailModal'); if (!modal) return; modal.querySelector('[data-detail-title]').textContent = item.dataset.description; modal.querySelector('[data-detail-category]').textContent = item.dataset.category; modal.querySelector('[data-detail-date]').textContent = item.dataset.date; modal.querySelector('[data-detail-description]').textContent = item.dataset.description; modal.querySelector('[data-detail-amount]').textContent = (item.dataset.type === 'income' ? '+ Rp ' : '- Rp ') + item.dataset.amount; modal.querySelector('[data-detail-type]').textContent = item.dataset.type === 'income' ? 'Pemasukan' : 'Pengeluaran'; modal.querySelector('[data-detail-type]').className = 'detail-type ' + item.dataset.type; const image = modal.querySelector('[data-detail-receipt]'), wrap = modal.querySelector('[data-detail-receipt-wrap]'), empty = modal.querySelector('[data-detail-no-receipt]'); if (item.dataset.receipt) { image.src = item.dataset.receipt; wrap.hidden = false; empty.hidden = true; } else { image.removeAttribute('src'); wrap.hidden = true; empty.hidden = false; } modal.showModal(); }));
document.querySelectorAll('dialog').forEach(dialog => {
    dialog.addEventListener('click', event => { if (event.target === dialog) closeModal(dialog); });
    dialog.addEventListener('cancel', event => { event.preventDefault(); closeModal(dialog); });
});
document.querySelectorAll('dialog .close').forEach(button => button.addEventListener('click', () => closeModal(button.closest('dialog'))));
document.querySelectorAll('[data-select]').forEach(select => {
    const trigger = select.querySelector('.modern-select-trigger'), hidden = select.querySelector('input[type="hidden"]'), label = select.querySelector('[data-select-label]');
    trigger.addEventListener('click', event => { event.stopPropagation(); document.querySelectorAll('[data-select].is-open').forEach(other => { if (other !== select) other.classList.remove('is-open'); }); select.classList.toggle('is-open'); });
    select.querySelectorAll('[data-value]').forEach(option => option.addEventListener('click', () => { hidden.value = option.dataset.value; label.textContent = option.childNodes[0].textContent.trim(); select.querySelectorAll('[data-value]').forEach(item => item.classList.remove('selected')); option.classList.add('selected'); select.classList.remove('is-open'); select.dispatchEvent(new CustomEvent('select:changed', { detail: option.dataset.value })); }));
});
document.querySelectorAll('.period-filter select').forEach(select => { const wrapper = document.createElement('div'); wrapper.className = 'period-dropdown'; const trigger = document.createElement('button'); trigger.type = 'button'; trigger.className = 'period-dropdown-trigger'; trigger.innerHTML = `<span>${select.options[select.selectedIndex].text}</span><b>⌄</b>`; const menu = document.createElement('div'); menu.className = 'period-dropdown-menu'; [...select.options].forEach(option => { const item = document.createElement('button'); item.type = 'button'; item.textContent = option.text; item.className = option.selected ? 'selected' : ''; item.addEventListener('click', () => { select.value = option.value; trigger.querySelector('span').textContent = option.text; menu.querySelectorAll('button').forEach(button => button.classList.remove('selected')); item.classList.add('selected'); wrapper.classList.remove('is-open'); select.dispatchEvent(new Event('change', { bubbles: true })); }); menu.appendChild(item); }); trigger.addEventListener('click', event => { event.stopPropagation(); document.querySelectorAll('.period-dropdown.is-open').forEach(other => { if (other !== wrapper) other.classList.remove('is-open'); }); wrapper.classList.toggle('is-open'); }); wrapper.append(trigger, menu); select.hidden = true; select.after(wrapper); });
document.addEventListener('click', () => document.querySelectorAll('.period-dropdown.is-open').forEach(dropdown => dropdown.classList.remove('is-open')));
document.addEventListener('click', () => document.querySelectorAll('[data-select].is-open').forEach(select => select.classList.remove('is-open')));
const typeSelect = document.querySelector('[data-select][data-name="type"]'), categorySelect = document.querySelector('[data-select][data-name="category_id"]');
if (typeSelect && categorySelect) typeSelect.addEventListener('select:changed', event => { const first = [...categorySelect.querySelectorAll('[data-value]')].find(option => option.dataset.type === event.detail); categorySelect.querySelectorAll('[data-value]').forEach(option => { option.hidden = option.dataset.type !== event.detail; }); if (first) first.click(); });
document.querySelectorAll('[data-rupiah]').forEach(input => input.addEventListener('input', () => { const digits = input.value.replace(/\D/g, ''); input.value = digits ? 'Rp ' + Number(digits).toLocaleString('id-ID') : ''; }));
document.querySelectorAll('form').forEach(form => form.addEventListener('submit', () => form.querySelectorAll('[data-rupiah]').forEach(input => { input.value = input.value.replace(/\D/g, ''); })));
document.querySelectorAll('[data-receipt-input]').forEach(input => input.addEventListener('change', () => { const preview = input.parentElement.querySelector('[data-receipt-preview]'), file = input.files[0]; if (!file) { preview.textContent = '＋ Pilih foto struk atau bukti transaksi'; return; } preview.innerHTML = `<img src="${URL.createObjectURL(file)}" alt="Preview bukti"> <span>${file.name}</span>`; }));
document.querySelectorAll('[data-copy-pairing]').forEach(button => button.addEventListener('click', async () => { const code = document.querySelector('[data-pairing-code]')?.textContent.trim(); if (!code) return; await navigator.clipboard.writeText('/hubungkan ' + code); toast.fire({ icon: 'success', title: 'Perintah pairing berhasil disalin.' }); button.textContent = 'Tersalin ✓'; setTimeout(() => button.textContent = 'Salin kode', 1800); }));
document.querySelectorAll('[data-share-telegram]').forEach(button => button.addEventListener('click', () => { const code = document.querySelector('[data-pairing-code]')?.textContent.trim(); if (code) window.open('https://t.me/share/url?url=&text=' + encodeURIComponent('/hubungkan ' + code), '_blank', 'noopener'); }));
const toast = Swal.mixin({ toast: true, position: 'top-end', showConfirmButton: false, timer: 3000, timerProgressBar: true, customClass: { popup: 'swal-keuangan' } });
const successMessage = @json(session('success'));
const errorMessages = @json($errors->all());
if (successMessage) toast.fire({ icon: 'success', title: successMessage });
if (errorMessages.length) toast.fire({ icon: 'error', title: errorMessages[0] });
document.querySelectorAll('.transaction-row form .icon-button, .category-actions form .icon-button, .members-table form .icon-button').forEach(button => { button.classList.add('delete-button'); button.textContent = ''; const icon = document.createElement('span'); icon.className = 'material-symbols-rounded'; icon.textContent = 'delete_forever'; icon.setAttribute('aria-hidden', 'true'); button.appendChild(icon); });
document.querySelectorAll('.transaction-row form[data-modern-delete]').forEach(form => { form.addEventListener('submit', event => { event.preventDefault(); Swal.fire({ title: 'Hapus transaksi ini?', text: 'Data yang dihapus tidak dapat dikembalikan.', icon: 'warning', showCancelButton: true, confirmButtonText: 'Ya, hapus', cancelButtonText: 'Batal', reverseButtons: true, confirmButtonColor: '#ef3340', cancelButtonColor: '#887d82', customClass: { popup: 'swal-keuangan' } }).then(async result => { if (!result.isConfirmed) return; const response = await fetch(form.action, { method: 'POST', headers: { 'X-CSRF-TOKEN': form.querySelector('input[name=_token]').value, 'X-HTTP-Method-Override': 'DELETE', 'Accept': 'application/json' } }); if (!response.ok) { toast.fire({ icon: 'error', title: 'Transaksi gagal dihapus.' }); return; } const row = form.closest('.transaction-row'); row?.remove(); document.querySelectorAll('.transactions .transaction-row').forEach((item, index) => { const number = item.querySelector('.transaction-number'); if (number) number.textContent = String(index + 1).padStart(2, '0'); }); toast.fire({ icon: 'success', title: 'Transaksi berhasil dihapus.' }); }); }); });
document.querySelectorAll('.transaction-row form:not([data-modern-delete]), .category-actions form, .members-table form').forEach(form => { if (!form.querySelector('.delete-button')) return; form.addEventListener('submit', event => { event.preventDefault(); Swal.fire({ title: 'Hapus data ini?', text: 'Data yang dihapus tidak dapat dikembalikan.', icon: 'warning', showCancelButton: true, confirmButtonText: 'Ya, hapus', cancelButtonText: 'Batal', reverseButtons: true, confirmButtonColor: '#ef3340', cancelButtonColor: '#887d82', customClass: { popup: 'swal-keuangan' } }).then(result => { if (result.isConfirmed) form.submit(); }); }); });
if (new URLSearchParams(window.location.search).get('view') === 'ledger') { const params = new URLSearchParams(window.location.search); const controls = document.querySelector('.ledger-controls'); const month = params.get('month') || new Date().getMonth() + 1; const year = params.get('year') || new Date().getFullYear(); const search = params.get('search') || ''; if (controls && !controls.querySelector('[data-ledger-tools]')) { const tools = document.createElement('div'); tools.dataset.ledgerTools = 'true'; tools.className = 'ledger-tools'; const searchForm = document.createElement('form'); searchForm.method = 'get'; searchForm.action = '/dashboard'; searchForm.className = 'ledger-search'; searchForm.innerHTML = '<input type="hidden" name="view" value="ledger"><input type="hidden" name="month" value="' + month + '"><input type="hidden" name="year" value="' + year + '"><input name="search" value="' + search.replace(/&/g, '&amp;').replace(/"/g, '&quot;') + '" placeholder="Cari transaksi..."><button type="submit">⌕</button>'; const csv = document.createElement('a'); csv.href = '/reports/ledger/export?month=' + encodeURIComponent(month) + '&year=' + encodeURIComponent(year) + '&search=' + encodeURIComponent(search); csv.className = 'button light-button export-ledger'; csv.textContent = '↓ CSV'; const pdf = document.createElement('a'); pdf.href = '/reports/ledger/pdf?month=' + encodeURIComponent(month) + '&year=' + encodeURIComponent(year) + '&search=' + encodeURIComponent(search); pdf.className = 'button primary export-ledger'; pdf.textContent = '↓ PDF'; tools.append(searchForm, csv, pdf); controls.appendChild(tools); } }
document.querySelectorAll('.ledger-search button').forEach(button => { button.innerHTML = '<i class="fi fi-rr-search" aria-hidden="true"></i>'; });
document.querySelectorAll('.transactions').forEach(container => { const rows = [...container.querySelectorAll('.transaction-row')]; const perPage = 10; if (rows.length <= perPage) return; const pages = Math.ceil(rows.length / perPage); let current = 1; const pagination = document.createElement('nav'); pagination.className = 'transaction-pagination'; pagination.setAttribute('aria-label', 'Pagination transaksi'); const render = () => { rows.forEach((row, index) => { row.hidden = index < (current - 1) * perPage || index >= current * perPage; }); pagination.innerHTML = ''; for (let page = 1; page <= pages; page++) { const button = document.createElement('button'); button.type = 'button'; button.textContent = page; button.className = page === current ? 'active' : ''; button.setAttribute('aria-label', 'Halaman ' + page); button.addEventListener('click', () => { current = page; render(); container.scrollIntoView({ behavior: 'smooth', block: 'start' }); }); pagination.appendChild(button); } }; container.after(pagination); render(); });
document.querySelectorAll('form[data-confirm]').forEach(form => form.addEventListener('submit', event => {
    event.preventDefault();
    Swal.fire({ title: form.dataset.confirmTitle || 'Hapus data ini?', text: form.dataset.confirmText || 'Data yang dihapus tidak dapat dikembalikan.', icon: 'warning', showCancelButton: true, confirmButtonText: 'Ya, hapus', cancelButtonText: 'Batal', reverseButtons: true, confirmButtonColor: '#ef3340', cancelButtonColor: '#887d82', customClass: { popup: 'swal-keuangan' } }).then(result => { if (result.isConfirmed) form.submit(); });
}));
</script></body></html>
