<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{{ $title ?? 'Keuangan' }}</title><link rel="stylesheet" href="https://cdn-uicons.flaticon.com/2.6.0/uicons-regular-rounded/css/uicons-regular-rounded.css">@if(file_exists(public_path('build/manifest.json'))) @vite(['resources/css/app.css','resources/js/app.js']) @endif<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script></head><body>
@auth
<header class="topbar"><a class="brand" href="{{ route('dashboard') }}"><span class="brand-mark">↗</span><span>Keuangan<span class="brand-dot">.</span></span></a><nav><a href="{{ route('dashboard') }}" class="{{ request()->routeIs('dashboard')?'active':'' }}">Ringkasan</a><a href="{{ route('categories') }}" class="{{ request()->routeIs('categories')?'active':'' }}">Kategori</a><a href="{{ route('profile') }}" class="{{ request()->routeIs('profile')?'active':'' }}">Profil</a><form method="post" action="{{ route('logout') }}">@csrf<button class="nav-logout">Keluar</button></form></nav><div class="user-chip"><span>{{ strtoupper(substr(auth()->user()->username,0,1)) }}</span>{{ auth()->user()->username }}</div></header>
<nav class="bottom-nav" aria-label="Navigasi utama mobile"><a href="{{ route('dashboard') }}" class="{{ request()->routeIs('dashboard')?'active':'' }}"><i class="fi fi-rr-home" aria-hidden="true"></i><small>Beranda</small></a><a href="{{ route('categories') }}" class="{{ request()->routeIs('categories')?'active':'' }}"><i class="fi fi-rr-apps" aria-hidden="true"></i><small>Kategori</small></a><a href="{{ route('dashboard',['open'=>'transaction']) }}" class="add-transaction" aria-label="Tambah transaksi"><i class="fi fi-rr-plus" aria-hidden="true"></i><small>Tambah</small></a><a href="{{ route('profile') }}" class="{{ request()->routeIs('profile')?'active':'' }}"><i class="fi fi-rr-user" aria-hidden="true"></i><small>Profil</small></a><form method="post" action="{{ route('logout') }}">@csrf<button><i class="fi fi-rr-sign-out-alt" aria-hidden="true"></i><small>Keluar</small></button></form></nav>
@endauth
<main class="page">{{ $slot ?? '' }} @yield('content')</main>
<script>
const closeModal = (dialog) => { if (!dialog || !dialog.open || dialog.classList.contains('closing')) return; dialog.classList.add('closing'); setTimeout(() => { dialog.classList.remove('closing'); dialog.close(); }, 180); };
document.querySelectorAll('[data-modal]').forEach(button => button.addEventListener('click', () => document.getElementById(button.dataset.modal)?.showModal()));
document.querySelectorAll('.add-transaction').forEach(button => button.addEventListener('click', event => { const modal = document.getElementById('transactionModal'); if (modal) { event.preventDefault(); modal.showModal(); } }));
if (new URLSearchParams(window.location.search).get('open') === 'transaction') document.getElementById('transactionModal')?.showModal();
document.querySelectorAll('[data-detail]').forEach(item => item.addEventListener('click', event => { if (event.target.closest('form,button,a')) return; const modal = document.getElementById('transactionDetailModal'); if (!modal) return; modal.querySelector('[data-detail-title]').textContent = item.dataset.description; modal.querySelector('[data-detail-category]').textContent = item.dataset.category; modal.querySelector('[data-detail-date]').textContent = item.dataset.date; modal.querySelector('[data-detail-description]').textContent = item.dataset.description; modal.querySelector('[data-detail-amount]').textContent = (item.dataset.type === 'income' ? '+ Rp ' : '- Rp ') + item.dataset.amount; modal.querySelector('[data-detail-type]').textContent = item.dataset.type === 'income' ? 'Pemasukan' : 'Pengeluaran'; modal.querySelector('[data-detail-type]').className = 'detail-type ' + item.dataset.type; const image = modal.querySelector('[data-detail-receipt]'), wrap = modal.querySelector('[data-detail-receipt-wrap]'), empty = modal.querySelector('[data-detail-no-receipt]'); if (item.dataset.receipt) { image.src = item.dataset.receipt; wrap.hidden = false; empty.hidden = true; } else { image.removeAttribute('src'); wrap.hidden = true; empty.hidden = false; } modal.showModal(); }));
document.querySelectorAll('dialog').forEach(dialog => {
    dialog.addEventListener('click', event => { if (event.target === dialog) closeModal(dialog); });
    dialog.addEventListener('cancel', event => { event.preventDefault(); closeModal(dialog); });
});
document.querySelectorAll('dialog .close').forEach(button => button.addEventListener('click', () => closeModal(button.closest('dialog'))));
document.querySelectorAll('[data-select]').forEach(select => {
    const trigger = select.querySelector('.modern-select-trigger'), hidden = select.querySelector('input[type="hidden"]'), label = select.querySelector('[data-select-label]');
    trigger.addEventListener('click', event => { event.stopPropagation(); document.querySelectorAll('[data-select].is-open').forEach(other => { if (other !== select) other.classList.remove('is-open'); }); select.classList.toggle('is-open'); });
    select.querySelectorAll('[data-value]').forEach(option => option.addEventListener('click', () => { hidden.value = option.dataset.value; label.textContent = option.childNodes[0].textContent.trim(); select.querySelectorAll('[data-value]').forEach(item => item.classList.remove('selected')); option.classList.add('selected'); select.classList.remove('is-open'); select.dispatchEvent(new CustomEvent('select:changed', { detail: option.dataset.value })); }));
});
document.querySelectorAll('.period-filter select').forEach(select => { const wrapper = document.createElement('div'); wrapper.className = 'period-dropdown'; const trigger = document.createElement('button'); trigger.type = 'button'; trigger.className = 'period-dropdown-trigger'; trigger.innerHTML = `<span>${select.options[select.selectedIndex].text}</span><b>⌄</b>`; const menu = document.createElement('div'); menu.className = 'period-dropdown-menu'; [...select.options].forEach(option => { const item = document.createElement('button'); item.type = 'button'; item.textContent = option.text; item.className = option.selected ? 'selected' : ''; item.addEventListener('click', () => { select.value = option.value; trigger.querySelector('span').textContent = option.text; menu.querySelectorAll('button').forEach(button => button.classList.remove('selected')); item.classList.add('selected'); wrapper.classList.remove('is-open'); select.dispatchEvent(new Event('change', { bubbles: true })); }); menu.appendChild(item); }); trigger.addEventListener('click', event => { event.stopPropagation(); document.querySelectorAll('.period-dropdown.is-open').forEach(other => { if (other !== wrapper) other.classList.remove('is-open'); }); wrapper.classList.toggle('is-open'); }); wrapper.append(trigger, menu); select.hidden = true; select.after(wrapper); });
document.addEventListener('click', () => document.querySelectorAll('.period-dropdown.is-open').forEach(dropdown => dropdown.classList.remove('is-open')));
document.addEventListener('click', () => document.querySelectorAll('[data-select].is-open').forEach(select => select.classList.remove('is-open')));
const typeSelect = document.querySelector('[data-select][data-name="type"]'), categorySelect = document.querySelector('[data-select][data-name="category_id"]');
if (typeSelect && categorySelect) typeSelect.addEventListener('select:changed', event => { const first = [...categorySelect.querySelectorAll('[data-value]')].find(option => option.dataset.type === event.detail); categorySelect.querySelectorAll('[data-value]').forEach(option => { option.hidden = option.dataset.type !== event.detail; }); if (first) first.click(); });
document.querySelectorAll('[data-rupiah]').forEach(input => input.addEventListener('input', () => { const digits = input.value.replace(/\D/g, ''); input.value = digits ? 'Rp ' + Number(digits).toLocaleString('id-ID') : ''; }));
document.querySelectorAll('form').forEach(form => form.addEventListener('submit', () => form.querySelectorAll('[data-rupiah]').forEach(input => { input.value = input.value.replace(/\D/g, ''); })));
document.querySelectorAll('[data-receipt-input]').forEach(input => input.addEventListener('change', () => { const preview = input.parentElement.querySelector('[data-receipt-preview]'), file = input.files[0]; if (!file) { preview.textContent = '＋ Pilih foto struk atau bukti transaksi'; return; } preview.innerHTML = `<img src="${URL.createObjectURL(file)}" alt="Preview bukti"> <span>${file.name}</span>`; }));
const toast = Swal.mixin({ toast: true, position: 'top-end', showConfirmButton: false, timer: 3000, timerProgressBar: true, customClass: { popup: 'swal-keuangan' } });
const successMessage = @json(session('success'));
const errorMessages = @json($errors->all());
if (successMessage) toast.fire({ icon: 'success', title: successMessage });
if (errorMessages.length) toast.fire({ icon: 'error', title: errorMessages[0] });
document.querySelectorAll('form[data-confirm]').forEach(form => form.addEventListener('submit', event => {
    event.preventDefault();
    Swal.fire({ title: form.dataset.confirmTitle || 'Hapus data ini?', text: form.dataset.confirmText || 'Data yang dihapus tidak dapat dikembalikan.', icon: 'warning', showCancelButton: true, confirmButtonText: 'Ya, hapus', cancelButtonText: 'Batal', reverseButtons: true, confirmButtonColor: '#ef3340', cancelButtonColor: '#887d82', customClass: { popup: 'swal-keuangan' } }).then(result => { if (result.isConfirmed) form.submit(); });
}));
</script></body></html>
