<?php

return [
    'payments' => 'Gaji / pembayaran',
    'account_balance_wallet' => 'Dompet',
    'savings' => 'Tabungan',
    'trending_up' => 'Pendapatan',
    'work' => 'Pekerjaan',
    'code' => 'Coding / pemrograman',
    'card_giftcard' => 'Bonus / hadiah',
    'restaurant' => 'Makanan',
    'local_grocery_store' => 'Kebutuhan dapur',
    'shopping_cart' => 'Belanja',
    'shopping_bag' => 'Belanja pribadi',
    'directions_car' => 'Mobil / transportasi',
    'two_wheeler' => 'Motor',
    'local_gas_station' => 'Bensin',
    'home' => 'Rumah',
    'receipt_long' => 'Tagihan',
    'lightbulb' => 'Listrik',
    'wifi' => 'Internet',
    'phone_android' => 'Pulsa / telepon',
    'medical_services' => 'Kesehatan',
    'school' => 'Pendidikan',
    'movie' => 'Hiburan',
    'sports_esports' => 'Game / olahraga',
    'fitness_center' => 'Kebugaran',
    'family_restroom' => 'Keluarga',
    'pets' => 'Hewan peliharaan',
    'checkroom' => 'Pakaian',
    'build' => 'Perawatan / perbaikan',
    'flight' => 'Perjalanan',
    'more_horiz' => 'Lainnya',
];
