<?php
namespace App\Http\Controllers;
use App\Models\Category; use App\Models\Transaction; use Illuminate\Http\Request; use Illuminate\Validation\Rule; use Illuminate\Support\Facades\Storage; use Illuminate\Support\Carbon;
class FinanceController extends Controller {
 public function index(Request $request) { $month = $request->integer('month', now()->month); $year = $request->integer('year', now()->year); $view = $request->input('view', 'modern'); $query=Transaction::with('category')->where('user_id',auth()->id())->whereYear('transaction_date',$year)->whereMonth('transaction_date',$month); $transactions=(clone $query); if ($view === 'ledger') $transactions->oldest('transaction_date')->oldest('id'); else $transactions->latest('transaction_date')->latest('id'); $transactions=$transactions->get(); $income=(clone $query)->where('type','income')->sum('amount'); $expense=(clone $query)->where('type','expense')->sum('amount'); $previousPeriod=Carbon::create($year,$month,1)->subMonth(); $previousQuery=Transaction::where('user_id',auth()->id())->whereYear('transaction_date',$previousPeriod->year)->whereMonth('transaction_date',$previousPeriod->month); $previousIncome=(clone $previousQuery)->where('type','income')->sum('amount'); $previousExpense=(clone $previousQuery)->where('type','expense')->sum('amount'); $carryForward=max(0,$previousIncome-$previousExpense); $ledgerIncome=$income+$carryForward; return view('dashboard', compact('transactions','income','expense','month','year','carryForward','ledgerIncome')); }
 public function store(Request $request) { $request->merge(['amount' => preg_replace('/\D+/', '', (string) $request->input('amount'))]); $data=$request->validate(['type'=>['required',Rule::in(['income','expense'])],'category_id'=>'required|exists:categories,id','transaction_date'=>'required|date','description'=>'required|max:255','amount'=>'required|numeric|min:1','receipt'=>'nullable|image|mimes:jpg,jpeg,png,webp|max:5120']); $category=Category::where('id',$data['category_id'])->where('user_id',auth()->id())->where('type',$data['type'])->where('is_active',true)->firstOrFail(); $data['user_id']=auth()->id(); if ($request->hasFile('receipt')) $data['receipt_path']=$request->file('receipt')->store('receipts','public'); unset($data['receipt']); Transaction::create($data); return back()->with('success','Transaksi berhasil ditambahkan.'); }
 public function destroy(Transaction $transaction) { abort_unless($transaction->user_id===auth()->id(),403); if ($transaction->receipt_path) Storage::disk('public')->delete($transaction->receipt_path); $transaction->delete(); return back()->with('success','Transaksi dihapus.'); }
 public function categories() { $categories=Category::where('user_id',auth()->id())->orderBy('type')->orderBy('name')->get(); return view('categories',compact('categories')); }
 public function categoryStore(Request $request) { $data=$request->validate(['name'=>'required|max:80','type'=>['required',Rule::in(['income','expense'])]]); Category::create([...$data,'user_id'=>auth()->id()]); return back()->with('success','Kategori ditambahkan.'); }
 public function categoryUpdate(Request $request, Category $category) { abort_unless($category->user_id===auth()->id(),403); $data=$request->validate(['name'=>'required|max:80']); $category->update($data); return back()->with('success','Kategori diperbarui.'); }
 public function categoryDestroy(Category $category) { abort_unless($category->user_id===auth()->id(),403); if($category->transactions()->exists()) $category->update(['is_active'=>false]); else $category->delete(); return back()->with('success',$category->is_active?'Kategori dihapus.':'Kategori dinonaktifkan karena sudah dipakai.'); }
 public function profile() { return view('profile'); }
 public function profileUpdate(Request $request) { $data=$request->validate(['username'=>['required','alpha_dash',Rule::unique('users')->ignore(auth()->id())],'password'=>'nullable|min:6|confirmed']); auth()->user()->update(array_filter($data)); return back()->with('success','Profil berhasil diperbarui.'); }
}
