<?php
namespace App\Http\Controllers;
use App\Models\SystemSetting; use Illuminate\Http\Request; use Illuminate\Support\Facades\Http;
class SettingsController extends Controller {
 private function owner(){ return \App\Models\Wallet::shared() ?? abort(500, 'Wallet utama belum tersedia.'); }
 private function setting(string $key,?string $fallback=null):?string{return SystemSetting::read($key,$fallback);}
 private function telegramUrl(string $method):string{return 'https://api.telegram.org/bot'.$this->setting('telegram_bot_token',config('services.telegram.bot_token')).'/'.$method;}
 public function index(){ $this->owner(); $telegramConfigured=(bool)$this->setting('telegram_bot_token',config('services.telegram.bot_token')); $groqConfigured=(bool)$this->setting('groq_api_key',config('services.groq.api_key')); $webhook=null; if($telegramConfigured){try{$webhook=Http::timeout(8)->get($this->telegramUrl('getWebhookInfo'))->json('result');}catch(\Throwable $e){$webhook=['last_error_message'=>$e->getMessage()];}} return view('settings',compact('telegramConfigured','groqConfigured','webhook')); }
 public function saveCredentials(Request $request){$this->owner();$data=$request->validate(['telegram_bot_token'=>'nullable|string|max:255','telegram_webhook_secret'=>'nullable|string|max:255','groq_api_key'=>'nullable|string|max:255','groq_model'=>'nullable|string|max:100']);foreach(['telegram_bot_token','telegram_webhook_secret','groq_api_key','groq_model'] as $key)if(filled($data[$key]??null))SystemSetting::write($key,$data[$key]);return redirect()->route('settings')->with('success','Pengaturan API berhasil disimpan secara terenkripsi.');}
 public function syncWebhook(){$this->owner();if(!$this->setting('telegram_bot_token',config('services.telegram.bot_token')))return redirect()->route('settings')->withErrors(['telegram'=>'Token bot belum diisi.']);$response=Http::timeout(15)->post($this->telegramUrl('setWebhook'),['url'=>rtrim(config('app.url'),'/').'/telegram/webhook','secret_token'=>$this->setting('telegram_webhook_secret',config('services.telegram.webhook_secret')),'drop_pending_updates'=>false]);if(!$response->successful()||!$response->json('ok'))return redirect()->route('settings')->withErrors(['telegram'=>$response->json('description','Gagal menyinkronkan webhook.')]);$commands=Http::timeout(15)->post($this->telegramUrl('setMyCommands'),['commands'=>[['command'=>'start','description'=>'Mulai dan lihat menu bantuan'],['command'=>'menu','description'=>'Tampilkan menu bot'],['command'=>'saldo','description'=>'Lihat saldo bulan ini'],['command'=>'laporan','description'=>'Lihat ringkasan keuangan'],['command'=>'export','description'=>'Export laporan PDF'],['command'=>'analisa','description'=>'Analisa kondisi keuangan'],['command'=>'pemasukan','description'=>'Lihat total pemasukan'],['command'=>'pengeluaran','description'=>'Lihat total pengeluaran'],['command'=>'transaksi','description'=>'Lihat transaksi terbaru'],['command'=>'kategori','description'=>'Kelola kategori keuangan'],['command'=>'bantuan','description'=>'Panduan penggunaan bot'],['command'=>'batal','description'=>'Batalkan transaksi']]]);return $commands->successful()&&$commands->json('ok')?redirect()->route('settings')->with('success','Webhook dan menu Telegram berhasil disinkronkan.'):redirect()->route('settings')->withErrors(['telegram'=>$commands->json('description','Webhook berhasil, tetapi menu Telegram gagal disinkronkan.')]);}
 public function removeWebhook(){$this->owner();if(!$this->setting('telegram_bot_token',config('services.telegram.bot_token')))return redirect()->route('settings')->withErrors(['telegram'=>'Token bot belum diisi.']);$response=Http::timeout(15)->post($this->telegramUrl('deleteWebhook'));return $response->successful()&&$response->json('ok')?redirect()->route('settings')->with('success','Webhook berhasil dihapus.'):redirect()->route('settings')->withErrors(['telegram'=>$response->json('description','Gagal menghapus webhook.')]);}
 public function testTelegram(){$this->owner();if(!$this->setting('telegram_bot_token',config('services.telegram.bot_token')))return redirect()->route('settings')->withErrors(['telegram'=>'Token bot belum diisi.']);$response=Http::timeout(15)->get($this->telegramUrl('getMe'));return $response->successful()&&$response->json('ok')?redirect()->route('settings')->with('success','Koneksi Telegram berhasil. Bot: @'.$response->json('result.username')):redirect()->route('settings')->withErrors(['telegram'=>$response->json('description','Koneksi Telegram gagal.')]);}
 public function testGroq(Request $request){$this->owner();$key=$this->setting('groq_api_key',config('services.groq.api_key'));if(!$key)return redirect()->route('settings')->withErrors(['groq'=>'API key Groq belum diisi.']);$response=Http::timeout(30)->withToken($key)->post('https://api.groq.com/openai/v1/chat/completions',['model'=>$this->setting('groq_model',config('services.groq.model')),'temperature'=>0,'messages'=>[['role'=>'system','content'=>'Kamu adalah parser transaksi keuangan. Jawab ringkas dalam Bahasa Indonesia. Jelaskan jenis transaksi, deskripsi, nominal, dan tanggal yang kamu pahami. Jangan menyimpan data.'],['role'=>'user','content'=>$request->input('text','makan 10k kemarin')]]]);if(!$response->successful())return redirect()->route('settings')->withErrors(['groq'=>$response->json('error.message','Tes Groq gagal.')]);return redirect()->route('settings')->with('groq_test',$response->json('choices.0.message.content','Tidak ada respons.'))->with('success','Tes Groq berhasil.');}
}
