<?php
namespace App\Http\Controllers;
use App\Models\PendingTransaction; use App\Models\TelegramConnection; use App\Models\TelegramPairingCode; use App\Models\TelegramUpdate; use App\Models\SystemSetting; use App\Models\Transaction; use App\Services\CategoryResolver; use App\Services\GroqTransactionParser; use App\Services\TransactionInputNormalizer; use Illuminate\Http\Request; use Illuminate\Support\Facades\Http; use Illuminate\Support\Facades\Log;
class TelegramWebhookController extends Controller {
 public function __construct(private GroqTransactionParser $parser,private TransactionInputNormalizer $normalizer,private CategoryResolver $categories){}
 private function token():?string{return SystemSetting::read('telegram_bot_token',config('services.telegram.bot_token'));}
 private function send(string $chatId,string $text,?array $keyboard=null):void{if($chatId===''||!$this->token())return;try{$data=['chat_id'=>$chatId,'text'=>$text];if($keyboard)$data['reply_markup']=json_encode(['inline_keyboard'=>$keyboard]);Http::timeout(10)->post('https://api.telegram.org/bot'.$this->token().'/sendMessage',$data);}catch(\Throwable $e){Log::error('Telegram sendMessage gagal',['error'=>$e->getMessage()]);}}
 private function answerCallback(string $id):void{if(!$this->token())return;Http::timeout(10)->post('https://api.telegram.org/bot'.$this->token().'/answerCallbackQuery',['callback_query_id'=>$id]);}
 public function handle(Request $request){$expected=(string)SystemSetting::read('telegram_webhook_secret',config('services.telegram.webhook_secret'));if($expected===''||!hash_equals($expected,(string)$request->header('X-Telegram-Bot-Api-Secret-Token')))return response()->json(['ok'=>false],403);$updateId=$request->integer('update_id');if(!$updateId)return response()->json(['ok'=>true]);if(TelegramUpdate::where('update_id',$updateId)->exists())return response()->json(['ok'=>true,'duplicate'=>true]);$callback=$request->input('callback_query');$message=$request->input('message',[]);$chatId=(string)($callback['message']['chat']['id']??$message['chat']['id']??'');TelegramUpdate::create(['update_id'=>$updateId,'chat_id'=>$chatId,'processed_at'=>now()]);if($callback){$this->handleCallback($chatId,(string)($callback['data']??''),(string)($callback['id']??''));return response()->json(['ok'=>true]);}$text=trim((string)($message['text']??''));$from=$message['from']??[];if(preg_match('/^\/start(?:@\w+)?/i',$text))$this->send($chatId,"Halo! Saya bot Keuangan. Hubungkan akun dengan mengirim:\n\n/hubungkan KODE\n\nKODE dibuat dari menu Telegram di website.");elseif(preg_match('/^\/hubungkan(?:@\w+)?\s+([A-Z0-9]{8})$/i',$text,$match))$this->pair($chatId,strtoupper($match[1]),$from);elseif(preg_match('/^\/(batal|cancel)(?:@\w+)?/i',$text)){$pending=PendingTransaction::where('chat_id',$chatId)->where('status','pending')->latest()->first();if($pending)$pending->update(['status'=>'cancelled']);$this->send($chatId,'Transaksi dibatalkan.');}elseif(TelegramConnection::where('chat_id',$chatId)->where('is_active',true)->exists())$this->parseTransaction($chatId,$text);else $this->send($chatId,'Akun Telegram ini belum terhubung. Gunakan /start untuk melihat cara pairing.');return response()->json(['ok'=>true]);}
 private function pair(string $chatId,string $code,array $from):void{$pairing=TelegramPairingCode::with('wallet')->where('code',$code)->whereNull('used_at')->where('expires_at','>',now())->first();if(!$pairing){$this->send($chatId,'Kode pairing tidak valid atau sudah kedaluwarsa. Buat kode baru dari website.');return;}$existing=TelegramConnection::where('chat_id',$chatId)->where('is_active',true)->first();if($existing&&$existing->wallet_id!==$pairing->wallet_id){$this->send($chatId,'Telegram ini sudah terhubung ke dompet lain. Putuskan koneksi lama terlebih dahulu.');return;}TelegramConnection::updateOrCreate(['chat_id'=>$chatId],['wallet_id'=>$pairing->wallet_id,'user_id'=>$pairing->user_id,'telegram_username'=>$from['username']??null,'telegram_name'=>trim(($from['first_name']??'').' '.($from['last_name']??'')),'is_active'=>true,'connected_at'=>now()]);$pairing->update(['used_at'=>now()]);$this->send($chatId,"Berhasil terhubung ke {$pairing->wallet->name}. Coba kirim: makan 10k kemarin");}
 private function parseTransaction(string $chatId,string $text):void{$connection=TelegramConnection::where('chat_id',$chatId)->where('is_active',true)->first();try{$now=now()->timezone('Asia/Jakarta');$parsed=$this->parser->parse($text,$now->toDateString(),$now->month,$now->year);if($parsed['intent']!=='create_transaction'||!in_array($parsed['type'],['income','expense'],true))throw new \RuntimeException('Saya belum memahami ini sebagai transaksi pemasukan atau pengeluaran.');if(!empty($parsed['missing_fields']))throw new \RuntimeException('Data belum lengkap: '.implode(', ',$parsed['missing_fields']).'.');$amount=$this->normalizer->amount($parsed['amount']);$date=$this->normalizer->date($parsed['date_expression'],$now,$now->month,$now->year);$category=$this->categories->find($connection->wallet,$parsed['type'],$parsed['category'].' '.$parsed['description']);if(!$category)throw new \RuntimeException('Kategori belum ditemukan. Tambahkan kategori yang sesuai dari website.');$pending=PendingTransaction::create(['wallet_id'=>$connection->wallet_id,'user_id'=>$connection->user_id,'chat_id'=>$chatId,'payload'=>['category_id'=>$category->id,'type'=>$parsed['type'],'transaction_date'=>$date,'description'=>$parsed['description'],'amount'=>$amount],'expires_at'=>now()->addMinutes(10)]);$label=$parsed['type']==='income'?'Pemasukan':'Pengeluaran';$this->send($chatId,"Saya memahami:\n\nJenis: {$label}\nKategori: {$category->name}\nKeterangan: {$parsed['description']}\nNominal: Rp ".number_format($amount,0,',','.')."\nTanggal: ".date('d/m/Y',strtotime($date))."\n\nSimpan transaksi ini?",[[['text'=>'Ya, simpan','callback_data'=>'pending:save:'.$pending->id],['text'=>'Batal','callback_data'=>'pending:cancel:'.$pending->id]]]);}catch(\Throwable $e){$this->send($chatId,$e->getMessage());}}
 private function handleCallback(string $chatId,string $data,string $callbackId):void{$this->answerCallback($callbackId);if(!preg_match('/^pending:(save|cancel):(\d+)$/',$data,$match))return;$pending=PendingTransaction::where('id',$match[2])->where('chat_id',$chatId)->where('status','pending')->first();if(!$pending||!$pending->isValid()){$this->send($chatId,'Konfirmasi sudah kedaluwarsa. Silakan kirim ulang transaksi.');return;}if($match[1]==='cancel'){$pending->update(['status'=>'cancelled']);$this->send($chatId,'Transaksi dibatalkan.');return;}Transaction::create(array_merge($pending->payload,['user_id'=>$pending->user_id,'wallet_id'=>$pending->wallet_id]));$pending->update(['status'=>'saved']);$this->send($chatId,'Transaksi berhasil disimpan ke Dompet Keluarga.');}
}
